from django.contrib import admin
from .models import person, body_style, make, transmission_type, drive_train, fuel_type, engine, drive, model, car, mImage, theme, favourite, Category, blog_entry, trim, trim_year, slide, plans, comentario2, distribuidor, propiedad, tipo_oferta, tipo_alquiler, tipo_propiedad, tipo_objeto, anuncio, tipo_image, estado_propiedad, pais, pais_estado, ciudad, car2, contacto, categoria, informacion_blog  
admin.site.register(person)
admin.site.register(propiedad)
admin.site.register(tipo_oferta)
admin.site.register(tipo_alquiler)
admin.site.register(tipo_propiedad)
admin.site.register(tipo_objeto)
admin.site.register(tipo_image)
admin.site.register(estado_propiedad)
admin.site.register(pais)
admin.site.register(pais_estado)
admin.site.register(ciudad)
admin.site.register(anuncio)
admin.site.register(favourite)
admin.site.register(categoria)
admin.site.register(informacion_blog)
admin.site.register(plans)
admin.site.register(comentario2)
admin.site.register(contacto)
