# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-22 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20170206_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('deler', models.CharField(max_length=30)),
                ('clasifi', models.CharField(max_length=20)),
                ('comentario', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
