# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-23 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_distribuidor2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='distribuidor',
        ),
    ]
