# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-23 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_delete_distribuidor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comentario',
        ),
        migrations.DeleteModel(
            name='distribuidor2',
        ),
    ]
