# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-23 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_auto_20210323_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.ImageField(upload_to='dirt/')),
                ('clasificacion', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=2)),
                ('tipo', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=30)),
                ('ubicacion', models.CharField(max_length=90)),
            ],
        ),
    ]
