# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-03-24 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_distribuidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='transmission_des',
            field=models.TextField(),
        ),
    ]
