# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-07 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_auto_20210324_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario2',
            name='asunto',
            field=models.CharField(max_length=180),
        ),
    ]
