# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-07 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_auto_20210507_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario2',
            name='clasifi',
            field=models.CharField(max_length=160),
        ),
    ]
