# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-07 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_auto_20210507_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='titulo',
            field=models.CharField(max_length=210),
        ),
    ]
