# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-07 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_auto_20210507_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipo_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='anuncio/')),
                ('ranuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.anuncio')),
            ],
        ),
    ]
