# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-07 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_tipo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo_image',
            name='image',
            field=models.ImageField(upload_to='anuncio/propiedad/'),
        ),
    ]
