# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-07 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_auto_20210507_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='estado_propiedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='pais_estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.pais')),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='especificaciones',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncio',
            name='lat',
            field=models.CharField(default='1', max_length=140),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='lon',
            field=models.CharField(default='1', max_length=140),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='servicios',
            field=models.CharField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='pais_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.pais_estado'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncio',
            name='estado_pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.pais_estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anuncio',
            name='estado_propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.estado_propiedad'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.pais'),
        ),
    ]
