# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-07 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0025_auto_20210507_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='moneda',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
