# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-12 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0026_anuncio_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='image',
            field=models.ImageField(default=1, upload_to='anuncio/anuncio/'),
            preserve_default=False,
        ),
    ]
