# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-14 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_car2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car2',
            name='body_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.propiedad'),
        ),
    ]
