# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-14 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_auto_20210514_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car2',
            old_name='owner',
            new_name='dueno',
        ),
    ]
