# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-14 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_auto_20210514_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car2',
            old_name='body_s',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='car2',
            old_name='trim',
            new_name='tipo_objeto',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='model',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='year',
        ),
        migrations.AddField(
            model_name='car2',
            name='tipo_alquiler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.tipo_alquiler'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='tipo_propiedad',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
