# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-14 23:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0032_auto_20210514_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='car2',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='especificaciones',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='estado_pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.pais_estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='estado_propiedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.estado_propiedad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='image',
            field=models.ImageField(default=1, upload_to='anuncio2/anuncio2/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='lat',
            field=models.CharField(default='1', max_length=80),
        ),
        migrations.AddField(
            model_name='car2',
            name='lon',
            field=models.CharField(default='1', max_length=80),
        ),
        migrations.AddField(
            model_name='car2',
            name='moneda',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps.pais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='precio',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000000)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car2',
            name='servicios',
            field=models.CharField(default=1, max_length=8000),
            preserve_default=False,
        ),
    ]
