# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-15 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_auto_20210514_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='car2',
            name='titulo',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
