# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-15 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_car2_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car2',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='especificaciones',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='estado_pais',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='estado_propiedad',
        ),
        migrations.RemoveField(
            model_name='car2',
            name='pais',
        ),
    ]
