# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-15 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0038_auto_20210515_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.anuncio'),
        ),
    ]
