# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-17 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_auto_20210515_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=90)),
                ('apellido', models.CharField(max_length=90)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=90)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
