# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-17 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_auto_20210517_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.CharField(max_length=90),
        ),
    ]
