# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-05-21 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0045_anuncio_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
