# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-06-09 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0046_anuncio_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='youtube',
            field=models.CharField(default='#', max_length=80),
        ),
    ]
