# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-06-10 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0047_anuncio_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='youtube',
            field=models.TextField(default='#'),
        ),
    ]
